
#ifndef PMTV_CODEC_INTERFACE_TYPE_H
#define PMTV_CODEC_INTERFACE_TYPE_H

typedef enum PMTVCodec_InterfaceType
{
    PMTVCODEC_MPEG4 = 0,
    PMTVCODEC_INDEO,
    PMTVCODEC_QPEG,
    PMTVCODEC_RAW,
    PMTVCODEC_NBCODECTYPE
} PMTVCodec_InterfaceType;

#endif

